
############################################################
##### 请配置好数据库password后将本文件更名为application.yml #####
############################################################

server:
  servlet:
    context-path: /api
  port: 8989

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://m.mzz.pub:3306/machineversion?characterEncoding=utf-8&useSSL=true
#    dbcp2:
#      max-idle: 10
#      log-abandoned: true
#      remove-abandoned-on-borrow: true
#      remove-abandoned-timeout: 60
#    tomcat:
#      max-active: 15
#      remove-abandoned: true
#      log-abandoned: true
#    hikari:
#      max-lifetime: 86430000
#    sql-script-encoding: UTF-8
#spring.datasource.initialize = false
#


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.web.machineversion.entity